### ISSUE TITLE
10주차 Stack 부분 학습지 완료 (due: 10/16)

### ISSUE THREAD

**Issue by wonyoungpark94** [ProjectInTheClass/zipCheck#39]

**Comment by KunhoYoo** [comment]
<img width="413" alt="001" src="https://user-images.githubusercontent.com/67401080/96200776-ba980200-0f95-11eb-8766-a6d283170d18.png">
<img width="418" alt="002" src="https://user-images.githubusercontent.com/67401080/96200781-bd92f280-0f95-11eb-9f93-14739043b068.png">
